import { parseAbi } from "viem";

export default parseAbi([
  "constructor()",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event Burn(address indexed sender, uint256 amount0, uint256 amount1, address indexed to)",
  "event DrainWrongToken(address indexed token, address to)",
  "event FeePercentUpdated(uint16 token0FeePercent, uint16 token1FeePercent)",
  "event Mint(address indexed sender, uint256 amount0, uint256 amount1)",
  "event SetPairTypeImmutable()",
  "event SetStableSwap(bool prevStableSwap, bool stableSwap)",
  "event Skim()",
  "event Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)",
  "event Sync(uint112 reserve0, uint112 reserve1)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "function DOMAIN_SEPARATOR() view returns (bytes32)",
  "function FEE_DENOMINATOR() view returns (uint256)",
  "function MAX_FEE_PERCENT() view returns (uint256)",
  "function MINIMUM_LIQUIDITY() view returns (uint256)",
  "function PERMIT_TYPEHASH() view returns (bytes32)",
  "function allowance(address, address) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function burn(address to) returns (uint256 amount0, uint256 amount1)",
  "function decimals() view returns (uint8)",
  "function drainWrongToken(address token, address to)",
  "function factory() view returns (address)",
  "function getAmountOut(uint256 amountIn, address tokenIn) view returns (uint256)",
  "function getReserves() view returns (uint112 _reserve0, uint112 _reserve1, uint16 _token0FeePercent, uint16 _token1FeePercent)",
  "function initialize(address _token0, address _token1)",
  "function initialized() view returns (bool)",
  "function kLast() view returns (uint256)",
  "function mint(address to) returns (uint256 liquidity)",
  "function name() view returns (string)",
  "function nonces(address) view returns (uint256)",
  "function pairTypeImmutable() view returns (bool)",
  "function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
  "function precisionMultiplier0() view returns (uint256)",
  "function precisionMultiplier1() view returns (uint256)",
  "function setFeePercent(uint16 newToken0FeePercent, uint16 newToken1FeePercent)",
  "function setPairTypeImmutable()",
  "function setStableSwap(bool stable, uint112 expectedReserve0, uint112 expectedReserve1)",
  "function skim(address to)",
  "function stableSwap() view returns (bool)",
  "function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes data, address referrer)",
  "function symbol() view returns (string)",
  "function sync()",
  "function token0() view returns (address)",
  "function token0FeePercent() view returns (uint16)",
  "function token1() view returns (address)",
  "function token1FeePercent() view returns (uint16)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
]);
